# fly.toml app configuration file generated for petapptechnigo on 2023-08-06T14:05:33+03:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = "petapptechnigo"
primary_region = "arn"

[build]

[env]
PORT = "8080"
MONGO_URL = "mongodb+srv://sukiphan97:Nhung1912@cluster0.u4ldkxy.mongodb.net/?retryWrites=true&w=majority"



[experimental]
  auto_rollback = true

[http_service]
  internal_port = 8080
    http_checks = []
  processes = ["app"]

[[services]]
  http_checks = []
  internal_port = 8080 
  processes = ["app"]
  
 [[services.ports]]
    port = 80
    handlers = ["http"]
    force_https = true
